DirectoryPath: "_site"
ExternalTimeout: 30
IgnoreURLs:
  - http://localhost:4000
  - https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2
IgnoreInternalEmptyHash: true
