site_title: FlowCrypt Docs
url: "https://flowcrypt.com/"

homepage_title: FlowCrypt Docs
baseurl: "/docs"
destination: _site/docs

plugins:
- jekyll-sitemap

liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: true

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

exclude: ["vendor", "config.yml", ".gitignore", ".htmltest.yml", ".jekyll-metadata", ".vale.ini", "bootstrap", "build.sh", "scripts", "Gemfile", "Gemfile.lock", "LICENSE", "Makefile", "navgoco_license", "README.md"]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      sidebar_data: "sidebar-data.json"
